// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query_get_match.sql

package data

import (
	"context"
)

const getMatch = `-- name: GetMatch :one
SELECT id, name FROM matches
WHERE id = $1 LIMIT 1
`

type GetMatchRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetMatch(ctx context.Context, id int64) (GetMatchRow, error) {
	row := q.db.QueryRowContext(ctx, getMatch, id)
	var i GetMatchRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
