// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query_get_game.sql

package data

import (
	"context"
)

const getGame = `-- name: GetGame :one
SELECT id, name FROM games
WHERE id = $1 LIMIT 1
`

type GetGameRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetGame(ctx context.Context, id int64) (GetGameRow, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
