package main

import "fmt"

func genMsg(ch chan<- string) {
	ch <- "This is an autogenerated message"
}

func relayMsg(ch1 <-chan string, ch2 chan<- string) {
	// recv message on ch1
	msg := <-ch1

	// send it on ch2
	ch2 <- msg
}

func main() {
	// create ch1 and ch2
	ch1 := make(chan string)
	ch2 := make(chan string)

	// spine goroutine genMsg and relayMsg
	go genMsg(ch1)

	go relayMsg(ch1, ch2)

	// recv message on ch2
	v := <-ch2
	fmt.Printf("Got message: %s", v)
}
